import streamlit as st
from groq import Groq
import os
from datetime import datetime

# 🔐 Secure API key (from Streamlit Secrets)
api_key = os.getenv("GROQ_API_KEY")

if not api_key:
    st.error("❌ API key not found. Add GROQ_API_KEY in Streamlit secrets.")
    st.stop()

client = Groq(api_key=api_key)
MODEL = "llama-3.3-70b-versatile"

st.set_page_config(page_title="AI Code Reviewer", page_icon="🔍", layout="wide")

st.markdown("""
<style>
.stApp { background: linear-gradient(135deg, #0f172a, #1e293b);
         background-attachment: fixed; color: #e2e8f0; }
textarea { background:#141720 !important; color:#e2e8f0 !important; border-radius:10px !important; }
.stButton button { background: linear-gradient(135deg,#38bdf8,#818cf8) !important;
                   color:black !important; font-weight:700 !important; }
.download-section { background:#141720; border:1px solid #2d3148;
                    border-radius:12px; padding:16px; margin-top:16px; }
</style>
""", unsafe_allow_html=True)


def review_code(code, language):
    prompt = f"""You are an expert {language} code reviewer.
Analyze the code and provide a detailed review with these exact sections:

1. BUGS DETECTED
2. CODE QUALITY ISSUES
3. SEVERITY (Low/Medium/High for each issue)
4. SUGGESTIONS
5. IMPROVED CODE
6. EXPLANATION
7. CODE QUALITY SCORE: X/100

Code to review:
{code}"""

    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
        max_tokens=1500
    )
    return response.choices[0].message.content


def build_txt_report(code, language, result):
    """Build a plain text report for download."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""
╔══════════════════════════════════════════════════════════╗
║              AI CODE REVIEW REPORT                       ║
╚══════════════════════════════════════════════════════════╝

Generated  : {timestamp}
Language   : {language}
Model      : {MODEL}

══════════════════════════════════════════════════════════
ORIGINAL CODE
══════════════════════════════════════════════════════════
{code}

══════════════════════════════════════════════════════════
REVIEW RESULT
══════════════════════════════════════════════════════════
{result}

══════════════════════════════════════════════════════════
END OF REPORT
══════════════════════════════════════════════════════════
"""


def build_md_report(code, language, result):
    """Build a markdown report for download."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""# 🔍 AI Code Review Report

| Field     | Value |
|-----------|-------|
| Generated | {timestamp} |
| Language  | {language} |
| Model     | {MODEL} |

---

## 📝 Original Code
```{language.lower()}
{code}
```

---

## 📋 Review Result

{result}

---
*Generated by AI Code Reviewer powered by Groq + LLaMA 3.3 70B*
"""


# ── UI ────────────────────────────────────────────────────────────────────
st.title("🔍 AI Code Reviewer")
st.write("Fast, accurate code review powered by Groq + LLaMA 3.3 70B")

language   = st.selectbox("Select Language", ["Python", "Java", "C++", "JavaScript"])
code_input = st.text_area("Paste your code here", height=300)

if st.button("🚀 Review Code"):
    if not code_input.strip():
        st.warning("Please enter code")
    else:
        with st.spinner("Analyzing code..."):
            try:
                result = review_code(code_input, language)

                st.markdown("### 📋 Review Result")
                st.markdown(result)

                # ── Download section ──────────────────────────────────
                st.markdown("---")
                st.markdown("### ⬇️ Download Report")

                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                col1, col2 = st.columns(2)

                with col1:
                    st.download_button(
                        label="📄 Download as TXT",
                        data=build_txt_report(code_input, language, result),
                        file_name=f"code_review_{timestamp}.txt",
                        mime="text/plain",
                        use_container_width=True
                    )

                with col2:
                    st.download_button(
                        label="📝 Download as Markdown",
                        data=build_md_report(code_input, language, result),
                        file_name=f"code_review_{timestamp}.md",
                        mime="text/markdown",
                        use_container_width=True
                    )

            except Exception as e:
                st.error(f"Error: {e}")
